# Port
server:
  port: 9999

spring:
#  main:
#    # Отключение циклических зависимостей (крайне не рекомендуется)
#    allow-circular-references: true

  # PostgreSQL configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/imoon
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Sa2022@@!!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Show database query message in the console
    show-sql: true

    # Hibernate configuration for Macbook
#    hibernate:
#      ddl-auto: update

jwt:
  secret: 98f2bsj2m4va8fl2f0afq8df8fao8zbf58da76
  lifetime: 60m

admin:
  username: kosh
  password: kosh
